Blame when hook script can not be executed.
Signed-off-by: Florin Hillebrand <e0925917@student.tuwien.ac.at>

diff --git a/tools/git-pre-commit-hook b/tools/git-pre-commit-hook
--- a/tools/git-pre-commit-hook
+++ b/tools/git-pre-commit-hook
@@ -8,6 +8,10 @@ exec 1>&2
 #
 
 this=`pwd`
+if [ ! -d $GIT_WORK_TREE/tools ]; then
+  echo >&2 "Could not find tools directory."
+  exit 1
+fi
 cd $GIT_WORK_TREE/tools
 ./check_modelsim_project.sh
 ret=$?
